"""Privacy scoring service and Person 2 integration interface."""

from typing import Any, Dict, List, Optional

# Risk point weights for baseline scoring
RISK_POINTS = {
    "CRITICAL": 30,
    "HIGH": 15,
    "MEDIUM": 8,
    "LOW": 3,
}


def calculate_privacy_score(
    entities: List[Dict[str, Any]],
    document_text: str,
    gemini_summary: Optional[str] = None,
    gemini_risk_level: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Calculate privacy risk score (0-100) and risk level.
    Designed as a clean integration point for Person 2's custom scoring algorithms.

    Args:
        entities: List of merged PII entities.
        document_text: Raw extracted document text.
        gemini_summary: Optional summary generated by Gemini.
        gemini_risk_level: Optional risk level assessed by Gemini.

    Returns:
        Dict with keys:
        - risk_score: int (0-100)
        - risk_level: str ("LOW" | "MEDIUM" | "HIGH" | "CRITICAL")
        - summary: str
    """
    if not entities:
        return {
            "risk_score": 0,
            "risk_level": "LOW",
            "summary": "No personal identifiable information or sensitive credentials detected.",
        }

    raw_score = 0
    has_critical = False
    has_high = False

    for entity in entities:
        risk = str(entity.get("risk", "LOW")).upper()
        raw_score += RISK_POINTS.get(risk, 5)
        if risk == "CRITICAL":
            has_critical = True
        elif risk == "HIGH":
            has_high = True

    # Scale and cap score at 100
    risk_score = min(100, raw_score)

    # Determine risk level
    if has_critical or risk_score >= 70:
        computed_level = "CRITICAL"
    elif has_high or risk_score >= 40:
        computed_level = "HIGH"
    elif risk_score >= 15:
        computed_level = "MEDIUM"
    else:
        computed_level = "LOW"

    # If Gemini assessed a higher risk level, adopt it
    risk_levels_order = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    final_risk_level = computed_level
    if gemini_risk_level and gemini_risk_level in risk_levels_order:
        if risk_levels_order.index(gemini_risk_level) > risk_levels_order.index(computed_level):
            final_risk_level = gemini_risk_level

    # Formulate summary
    if gemini_summary and "unavailable" not in gemini_summary.lower() and "error" not in gemini_summary.lower():
        summary = gemini_summary
    else:
        types_found = list({e.get("type", "PII") for e in entities})
        summary = (
            f"Detected {len(entities)} sensitive entities across {len(types_found)} categories "
            f"({', '.join(types_found[:4])}). Document assessed with {final_risk_level} privacy exposure."
        )

    return {
        "risk_score": risk_score,
        "risk_level": final_risk_level,
        "summary": summary,
    }
